version: '3.8'

services:
  web:
    container_name: user
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - configs/conf.env

  db:
    container_name: user_db
    restart: on-failure
    image: postgres:latest
    env_file:
      - configs/db.env
    ports:
      - "5432:5432"