version: '3.8'

services:
  web:
    restart: on-failure
    build:
      context: ../../етз
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - ../../етз/configs/conf.env

  db:
    restart: on-failure
    image: postgres:latest
    env_file:
      - ../../етз/configs/db.env
    ports:
      - "5432:5432"